version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/sdoh_coordination_platform_client_production
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
    restart: unless-stopped
    command: >
      bash -c "bundle exec rails db:create db:migrate &&
               bundle exec rails server -b 0.0.0.0 -p 3000"

  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sdoh_coordination_platform_client_production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
